### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by FengHuaXing** [mesunhlf/FASTEN#1]
您好！
        非常感谢您撰写的这篇文章，我对此文章非常感兴趣，请问您方便提供一份文章的源代码吗？

**Comment by mesunhlf** [comment]
> 您好！ 非常感谢您撰写的这篇文章，我对此文章非常感兴趣，请问您方便提供一份文章的源代码吗？

你好，代码已经上传，感谢对本工作的关注。
